import { useState, useEffect, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import Card from '../../components/ui/Card'
import Button from '../../components/ui/Button'
import StatCard from '../../components/ui/StatCard'
import { useToast } from '../../components/ui/Toast'
import { HiClipboardList, HiDownload, HiChartBar, HiUserGroup, HiCurrencyRupee, HiCheckCircle, HiPlay } from 'react-icons/hi'
import { HiTrophy } from 'react-icons/hi2'
import { getTournamentReports, getTeams } from '../../services/tournamentService'

const downloadFile = (filename, content, mime) => {
    const blob = new Blob([content], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}

export default function TournamentReportsPage() {
    const { addToast } = useToast()
    const navigate = useNavigate()
    const [isLoading, setIsLoading] = useState(true)
    const [report, setReport] = useState({ tournamentStatusBreakdown: [], totalTeamsRegistered: 0, totalRevenue: 0, totalCommission: 0 })
    const [isExporting, setIsExporting] = useState('')

    const fetchReport = useCallback(async () => {
        setIsLoading(true)
        try {
            const res = await getTournamentReports()
            setReport(res.data || {})
        } catch (err) {
            addToast({ title: 'Load Failed', message: err.message || 'Failed to load tournament reports.', type: 'error' })
        } finally {
            setIsLoading(false)
        }
    }, [addToast])

    useEffect(() => { fetchReport() }, [fetchReport])

    const activeTournaments = (report.tournamentStatusBreakdown || [])
        .filter(g => ['APPROVED', 'ACTIVE', 'RUNNING', 'REGISTRATION_OPEN', 'UPCOMING'].includes(g.status))
        .reduce((sum, g) => sum + g.count, 0)

    const handleDownloadSummaryReport = (reportName, format) => {
        setIsExporting(reportName)
        try {
            const cleanName = reportName.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()
            const filename = `${cleanName}_${new Date().toISOString().slice(0, 10)}.${format}`
            const statusLines = (report.tournamentStatusBreakdown || []).map(g => `${g.status},${g.count}`).join('\n')

            let content
            if (format === 'csv') {
                content = `Report Name,${reportName}\nGenerated On,${new Date().toLocaleString()}\nPlatform,SportMatrix OS\n\nMetric,Value\nActive Tournaments,${activeTournaments}\nRegistered Teams,${report.totalTeamsRegistered}\nGross Income (INR),${report.totalRevenue}\nPlatform Commission (INR),${report.totalCommission}\n\nTournament Status,Count\n${statusLines}\n`
            } else {
                content = `=======================================================\nSPORTMATRIX OFFICIAL TOURNAMENT REPORT: ${reportName.toUpperCase()}\n=======================================================\nGenerated Date: ${new Date().toLocaleString()}\n\n1. OVERVIEW METRICS\n-------------------------------------------------------\n- Active Tournaments: ${activeTournaments}\n- Total Registered Teams: ${report.totalTeamsRegistered}\n- Gross Tournament Income: INR ${Number(report.totalRevenue).toLocaleString('en-IN')}\n- Platform Commission Collected: INR ${Number(report.totalCommission).toLocaleString('en-IN')}\n\n2. TOURNAMENT STATUS BREAKDOWN\n-------------------------------------------------------\n${(report.tournamentStatusBreakdown || []).map(g => `- ${g.status}: ${g.count}`).join('\n')}\n\n=======================================================\nGenerated by SportMatrix Tournament Management OS\n`
            }
            downloadFile(filename, content, format === 'csv' ? 'text/csv' : 'text/plain')
            addToast({ title: 'File Downloaded', message: `Report "${filename}" saved to your Downloads folder!`, type: 'success' })
        } finally {
            setIsExporting('')
        }
    }

    const handleDownloadRosterReport = async () => {
        setIsExporting('roster')
        try {
            const res = await getTeams()
            const teams = res.data || []
            const filename = `team_player_roster_report_${new Date().toISOString().slice(0, 10)}.csv`
            const header = 'Team Name,Tournament,Captain Name,Captain Email,Captain Mobile,Status,Player Count'
            const rows = teams.map(t => `"${t.teamName || ''}","${t.tournament?.title || ''}","${t.captainName || ''}","${t.captainEmail || ''}","${t.captainMobile || ''}","${t.status || ''}",${(t.players || []).length}`)
            downloadFile(filename, [header, ...rows].join('\n'), 'text/csv')
            addToast({ title: 'File Downloaded', message: `Report "${filename}" saved with ${teams.length} real registered teams.`, type: 'success' })
        } catch (err) {
            addToast({ title: 'Export Failed', message: err.message || 'Failed to export roster report.', type: 'error' })
        } finally {
            setIsExporting('')
        }
    }

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200/90 shadow-sm">
                <div>
                    <h1 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
                        <HiClipboardList className="text-emerald-600" /> Tournament Reports & Analytics
                    </h1>
                    <p className="text-slate-500 text-sm mt-0.5 font-medium">Export tournament summaries, financial reports, and team rosters from real platform data</p>
                </div>
            </div>

            {/* Stat Summary */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
                <StatCard title="Active Tournaments" value={isLoading ? '...' : String(activeTournaments)} icon={<HiChartBar className="text-emerald-600 w-6 h-6" />} />
                <StatCard title="Registered Teams" value={isLoading ? '...' : `${report.totalTeamsRegistered} Teams`} icon={<HiUserGroup className="text-emerald-500 w-6 h-6" />} />
                <StatCard title="Gross Tournament Income" value={isLoading ? '...' : `₹${Number(report.totalRevenue).toLocaleString('en-IN')}`} icon={<HiCurrencyRupee className="text-indigo-500 w-6 h-6" />} />
                <StatCard title="Platform Commission Collected" value={isLoading ? '...' : `₹${Number(report.totalCommission).toLocaleString('en-IN')}`} icon={<HiCheckCircle className="text-amber-500 w-6 h-6" />} />
            </div>

            {/* Report Download Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card className="p-6 space-y-4">
                    <div className="flex justify-between items-start">
                        <div>
                            <h3 className="font-extrabold text-slate-900 text-base">Comprehensive Tournament Report</h3>
                            <p className="text-xs text-slate-500 mt-1">Tournament status breakdown, team counts, and revenue summary</p>
                        </div>
                        <Button size="sm" disabled={isExporting === 'Comprehensive_Tournament_Report'} onClick={() => handleDownloadSummaryReport('Comprehensive_Tournament_Report', 'pdf')}>
                            <HiDownload className="w-4 h-4 mr-1" /> Export
                        </Button>
                    </div>
                </Card>

                <Card className="p-6 space-y-4">
                    <div className="flex justify-between items-start">
                        <div>
                            <h3 className="font-extrabold text-slate-900 text-base">Revenue & Commission Report</h3>
                            <p className="text-xs text-slate-500 mt-1">Real gross revenue and platform commission collected from tournament payments</p>
                        </div>
                        <Button size="sm" disabled={isExporting === 'Revenue_Commission_Report'} onClick={() => handleDownloadSummaryReport('Revenue_Commission_Report', 'csv')}>
                            <HiDownload className="w-4 h-4 mr-1" /> Export CSV
                        </Button>
                    </div>
                </Card>

                <Card className="p-6 space-y-4">
                    <div className="flex justify-between items-start">
                        <div>
                            <h3 className="font-extrabold text-slate-900 text-base">Team & Player Roster Report</h3>
                            <p className="text-xs text-slate-500 mt-1">Real registered team directory with captain contacts and player counts</p>
                        </div>
                        <Button size="sm" disabled={isExporting === 'roster'} onClick={handleDownloadRosterReport}>
                            <HiDownload className="w-4 h-4 mr-1" /> {isExporting === 'roster' ? 'Exporting...' : 'Export CSV'}
                        </Button>
                    </div>
                </Card>
            </div>

            {/* How to Check Match Details Section */}
            <div className="bg-gradient-to-r from-slate-900 via-slate-850 to-emerald-950 p-6 rounded-3xl text-white border border-emerald-500/30 shadow-lg space-y-4">
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
                    <div>
                        <h3 className="text-lg font-black text-white flex items-center gap-2">
                            <span>🏟️</span> How to Check & Manage Tournament Match Details
                        </h3>
                        <p className="text-xs text-slate-300 mt-0.5 font-medium">Access live scorecards, match fixtures, and bracket trees across the system</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                    <div
                        onClick={() => navigate('/admin/tournaments/fixtures')}
                        className="p-4 bg-slate-900/80 hover:bg-emerald-950/60 border border-slate-700/80 hover:border-emerald-400 rounded-2xl transition-all cursor-pointer space-y-1.5 group"
                    >
                        <div className="flex justify-between items-center">
                            <span className="font-black text-emerald-400 text-sm flex items-center gap-1.5">
                                <HiPlay className="w-4 h-4" /> 1. Playoff Bracket Tree
                            </span>
                            <span className="text-[10px] text-slate-400 font-mono group-hover:translate-x-1 transition-transform">View Tree ➔</span>
                        </div>
                        <p className="text-slate-300 leading-relaxed">
                            Navigate to <strong className="text-white font-mono">/admin/tournaments/fixtures</strong>. Click any match box in Quarter-Finals, Semi-Finals, or Finale to view & edit live scores, slot times, and status.
                        </p>
                    </div>

                    <div
                        onClick={() => navigate('/admin/tournaments/matches')}
                        className="p-4 bg-slate-900/80 hover:bg-emerald-950/60 border border-slate-700/80 hover:border-emerald-400 rounded-2xl transition-all cursor-pointer space-y-1.5 group"
                    >
                        <div className="flex justify-between items-center">
                            <span className="font-black text-emerald-400 text-sm flex items-center gap-1.5">
                                <HiTrophy className="w-4 h-4 text-amber-400" /> 2. All Matches Master Directory
                            </span>
                            <span className="text-[10px] text-slate-400 font-mono group-hover:translate-x-1 transition-transform">View Matches ➔</span>
                        </div>
                        <p className="text-slate-300 leading-relaxed">
                            Navigate to <strong className="text-white font-mono">/admin/tournaments/matches</strong>. View the complete table of all scheduled, live, and completed matches with venue & status badges.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}
